### ISSUE TITLE
Ability to distribute votes across multiple answers

### ISSUE THREAD

**Issue by jamesg1** [lesterchan/wp-polls#102]
Firstly great plugin! I managed to modify the code to suit a user case for a football WP site I run where the user distributes multiple votes (6) amongst one or many answers. The user completes the form by typing a number 1-6 into their answers. The user can only use 6 votes.

Would this feature be beneficial for the main project as an additional feature type when creating polls? My version of WP-Polls I had to change/disable some functionality in order for it to work, loop through the answers and add additional DB fields to store logs correctly. But would be nice to clean it up properly with better error messages.

If you reckon this feature is worth while I can make a start on a fork?

Thanks

**Comment by lesterchan** [comment]
Feel free to start a fork, this looks like a "survey type" of polls which is not what I envisioned the plugin to be =)

**Comment by jamesg1** [comment]
It wouldn't need to be entering in numbers could be clicking on a plus icon next to an answer. Would cover the usecase of multiple votes on one or more answers. jVoteSystem https://joomess.de/projects/jvotesystem has it 'Distribution of votes on different answers'
