### ISSUE TITLE
Stupid Question

### ISSUE THREAD

**Issue by LewisMaxwell** [lesterchan/wp-polls#106]
Lester,

Thanks for the plugin, considering using it but have a stupid question. In the options where you can select who to allow, it lets you limit to registered users. Where are the users defined, or are you referring to WordPress users? I want to restrict my polls to a predefined list of users and want to know how/where to set them up.

Thanks in advance.

Lewis Maxwell

**Comment by lesterchan** [comment]
Sorry that is not possible as the plugin is not designed for that use case.

**Comment by LewisMaxwell** [comment]
Why not, its a members blog and I want to restrict polling to only logged in users. Can you at least confirm that the "registered users" are WordPress users?

**Comment by lesterchan** [comment]
Because I don’t have that use case? 

Yeap members means WordPress registered users of your blog.

**Comment by LewisMaxwell** [comment]
Thanks, I saw another issue that seemed to confirm that it is the WordPress user. Knowing that, I should be able to make it do what I want. Thanks again.
