### ISSUE TITLE
Check if guest already voted

### ISSUE THREAD

**Issue by S1SYPHOS** [lesterchan/wp-polls#107]
Hey there,
great plugin, just one quick question: How could I check if IP and / or Cookie (current guest) already voted a poll? For example:

poll('2') already voted >link to its page gets disabled
poll('2') NOT voted >link to its page still accessible

Cheers!

**Comment by lesterchan** [comment]
`check_voted( 2 )`? https://github.com/lesterchan/wp-polls/blob/master/wp-polls.php#L327

**Comment by S1SYPHOS** [comment]
Thanks for clarification, maybe I'll send a PR with some additional documentation your way 🎷
