### ISSUE TITLE
CAPTCHA

### ISSUE THREAD

**Issue by mark-szabo** [lesterchan/wp-polls#109]
Can you please integrate Google's reCAPTCHA? https://www.google.com/recaptcha/intro/

We just had an attack with another polling plugin by a botnet and it'd be great if we could use this plugin and optionally enable CAPTCHA.

Thanks! :)

**Comment by mark-szabo** [comment]
So nope? 🤨🤔

**Comment by lesterchan** [comment]
Sorry nope, no intending for doing that =)
