### ISSUE TITLE
Button Class CSS

### ISSUE THREAD

**Issue by alfredderose** [lesterchan/wp-polls#110]
Maybe I'm mistaken, but it seems that button colors are not being picked up from either polls-css.css or from the theme. It looks like the class is perhaps not correct. Should this class not just be .button?

wp-polls.css
=================================================
.wp-polls .Buttons {
	border:1px solid #428bca;
	background-color: #428bca;

wp-polls.php
=================================================
	'<p style="text-align: center;"><input type="button" name="vote" value="   '.__('Vote', 'wp-polls').'   " class="Buttons" onclick="poll_vote(%POLL_ID%);" /></p>'.

**Comment by lesterchan** [comment]
The class name is Buttons is correct. Your theme style is properly overwriting it.
