### ISSUE TITLE
Show next poll after vote?

### ISSUE THREAD

**Issue by Soullighter** [lesterchan/wp-polls#111]
Is it possible to show next poll after user vote? I don't want to show user vote results after they vote

**Comment by lesterchan** [comment]
Nope, this feature doesn't exist in the plugin.

**Comment by Soullighter** [comment]
ah :-(
It's not possible even with some custom php <code> ?

**Comment by lesterchan** [comment]
This plugin is open source, you are free to fork and modify to implement it =)
