### ISSUE TITLE
Use translation files for wordpress >=4.0

### ISSUE THREAD

**Issue by IndianGhost** [lesterchan/wp-polls#113]
Hi @lesterchan :smile: , 
  I really liked your this plugin :1st_place_medal: I used it to create polls in English and actually I want to use the translation files for hebrew :
https://plugins.trac.wordpress.org/browser/wp-polls/i18n/wp-polls-he_IL.mo
https://plugins.trac.wordpress.org/browser/wp-polls/i18n/wp-polls-he_IL.po
I tried to add a WPLANG constant into wp-config.php but I got this message "Since wordpress 4.0 WPLANG constant is no longer needed"
Best regards,

**Comment by lesterchan** [comment]
WP-Polls uses GlotPress to translate, no longer po/mo file. https://translate.wordpress.org/projects/wp-plugins/wp-polls
