### ISSUE TITLE
Question: using this plugin for elections

### ISSUE THREAD

**Issue by mozboz** [lesterchan/wp-polls#115]
(Sorry to open a github issue, not sure how to contact authors to ask a question)

I'm looking for a plugin to run an election. I need the following:

- User must be registered user to vote
- User can only vote once in a particular election
- User can only vote for one candidate
- Administrator can see who has voted and who they voted for and totals for each candidate (option)

Is this plugin suitable?

Thank you!

mozboz

**Comment by lesterchan** [comment]
Nope.
