### ISSUE TITLE
[Question] Embeddable Poll outside of Wordpress ? with script or iframe ?

### ISSUE THREAD

**Issue by Steffi3rd** [lesterchan/wp-polls#119]
Hello! 

Do you know if this Poll plugin for Wordpress is embeddable? outside of WordPress? 

What I mean is I created the poll from Wordpress and I display it on an another site using `script` or `iframe` or `embed`? 

Thanks!

**Comment by lesterchan** [comment]
Sorry, the plugin is not designed to work outside of WordPress.
