### ISSUE TITLE
Get all posts

### ISSUE THREAD

**Issue by d-to-the-g-to-the-danny-g** [lesterchan/wp-polls#121]
Is there a method that gets all the polls as objects so I can loop through them?

**Comment by lesterchan** [comment]
Sorry, there is no such functions. You can query the DB directly
```SELECT * FROM $wpdb->pollsq WHERE $polls_type_sql ORDER BY pollq_id DESC```

You can take a look at https://github.com/lesterchan/wp-polls/blob/master/wp-polls.php#L915
