### ISSUE TITLE
Can't create poll with "Do NOT Expire This Poll" selection checked

### ISSUE THREAD

**Issue by isomjyri** [lesterchan/wp-polls#122]
I can't create poll with **Do NOT Expire This Poll** selection checked, I get the following error: ```WordPress database error `Incorrect integer value: '' for column 'pollq_expiry' at row 1 for query INSERT INTO `wp_pollsq` (`pollq_question`, `pollq_timestamp`, `pollq_totalvotes`, `pollq_active`, `pollq_expiry`, `pollq_multiple`, `pollq_totalvoters`) VALUES ('This is test question', '1545316518', 0, 1, '', 0, 0)`.```

Also, in `plugins/wp-polls/polls-add.php` at row 82, I get `Undefined variable: text`.

**Comment by lesterchan** [comment]
Fixed! try replacing polls-add.php with https://raw.githubusercontent.com/lesterchan/wp-polls/master/polls-add.php

**Comment by lesterchan** [comment]
Thanks, I have release the update which fixes it already =)
