### ISSUE TITLE
Ajax on password secured wp-admin folder

### ISSUE THREAD

**Issue by ei23-fxg** [lesterchan/wp-polls#137]
Hi,
is it possible to do the ajax stuff without the "admin_url('admin-ajax.php')" stuff?
I would like to have my wp-admin folder password secured with htaccess, but then public polls wont work.

**Comment by lesterchan** [comment]
Sadly, despite the name and location, that is the correct way to do it. You need to whitelist admin-ajax.php https://wordpress.stackexchange.com/questions/77407/how-does-admin-ajax-php-work

**Comment by ei23-fxg** [comment]
I learned something, thank you!
