### ISSUE TITLE
Add hooks for all templates rather than just voting form header, body & footer

### ISSUE THREAD

**Issue by Jaska** [lesterchan/wp-polls#138]
After looking at the source, creating new templates for forms with php is easy:

     add_filter( 'wp_polls_template_votebody_markup', 'mycallback', 10, 3 );

But there are only filters for wp_polls_template_voteheader_markup, wp_polls_template_votebody_markup and wp_polls_template_votefooter_markup.

How about all the other templates, mainly the result templates?

There is 'wp_polls_result_markup' filter for the entire result but would it be possible to have similar filters like the once I mentioned above?

Thanks!

**Comment by lesterchan** [comment]
Want to send a PR? The previous filters for markup were done by contributors.

**Comment by Jaska** [comment]
Ok, I'll look into it.

**Comment by Jaska** [comment]
Here you go :)

https://github.com/lesterchan/wp-polls/pull/139
