### ISSUE TITLE
Supports to get IP from nxging

### ISSUE THREAD

**Issue by heliobentzen** [lesterchan/wp-polls#36]
It's not possilbe get an IP using nxging as webserver. IP displayed is the same IP from host.

**Comment by lesterchan** [comment]
How is the IP being passed in the header? Most uses HTTP_X_FORWARDED_FOR if not REMOTE_IP

Upload this file https://gist.github.com/lesterchan/890b6a1d0b7e33d761b7 to your server, see if it does get the IP.

**Comment by heliobentzen** [comment]
In my log, for example, I saw all registers like this:

6Guest45.56.75.196
<https://proxy-nl.hide.me/go.php?u=pimVArG%2BpacUut9Ov%2BhhDMLRv%2BJpA5hjpA%3D%3D&b=5>
/
wellcloud.noticiasdeparauapebas.com05/02/2015 @ 02:047Guest45.56.75.196
<https://proxy-nl.hide.me/go.php?u=pimVArG%2BpacUut9Ov%2BhhDMLRv%2BJpA5hjpA%3D%3D&b=5>
/
wellcloud.noticiasdeparauapebas.com05/02/2015 @ 02:04

Hélio Bentzen
(094) 8150-4533

*Confidentiality Notice: The information contained in this email message,
including any attachment, is confidential and is intended only for the
person or entity to which it is addressed. If you are neither the intended
recipient nor the employee or agent responsible for delivering this message
to the intended recipient, you are hereby notified that you may not review,
retransmit, convert to hard copy, copy, use or distribute this email
message or any attachments to it. If you have received this email in error,
please contact the sender immediately and delete this message from any
computer or other data bank. Thank you.*

**Comment by heliobentzen** [comment]
I'm looking now this function:

if(!function_exists('get_ipaddress')) {
	function get_ipaddress() {
		if (empty($_SERVER["HTTP_X_FORWARDED_FOR"])) {
			$ip_address = $_SERVER["REMOTE_ADDR"];
		}
		} else {
			$ip_address = $_SERVER["HTTP_X_FORWARDED_FOR"];
		}
		if(strpos($ip_address, ',') !== false) {
			$ip_address = explode(',', $ip_address);
			$ip_address = $ip_address[0];
		}
		return esc_attr($ip_address);
	}
}

I tried use HTTP_X_REAL_IP instead REMOTE_ADDR, but get it empty.

**Comment by kim07** [comment]
:+1:
