### ISSUE TITLE
 unexpected output 

### ISSUE THREAD

**Issue by dsalcedo** [lesterchan/wp-polls#39]
The plugin generated 250 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.
Wordpres v4.1.1

**Comment by lesterchan** [comment]
I can't reproduced the problem on my end most likely it is s plugin conflict or theme conflict.

This is not a support forum but a developer centric website. if you post in here, I expect more details like the actual error message or what you did already.

Try this plugin.

**Comment by lesterchan** [comment]
Try this plugin https://wordpress.org/plugins/debug-plugin-activation-errors/
