### ISSUE TITLE
FORCE_SSL_ADMIN Wordpress option makes the plugin unusable (with a self-signed cert)

### ISSUE THREAD

**Issue by dfisek** [lesterchan/wp-polls#43]
Wordpress has a FORCE_SSL_ADMIN option where connections to the admin interface of Wordpress is forced to HTTPS.

This function doesn't force wp-admin/admin-ajax.php to SSL since many plugins (like wp-polls) use this for ajax calls.

However when wp-polls forms the URL for admin-ajax.php, it calls the admin_url() function which returns the admin interface URL in https (if FORCE_SSL_ADMIN is enabled).

At that time we have a mixed content, where the rest of the site is served through http and the admin-ajax.php is served through https. If the site doesn't have a SSL certificate that is trusted, the browser's default behavior is to block that https connection thus breaking wp-polls plugin.

The only fix I could apply was to use the home_url() function instead and hardcode the "wp-admin" directory (diff below).

<pre>
--- wp-polls.php.orig   2015-05-20 10:52:34.313748336 +0300
+++ wp-polls.php        2015-05-20 14:12:13.803681346 +0300
@@ -212,7 +212,7 @@
        $pollbar = get_option('poll_bar');
        wp_enqueue_script('wp-polls', plugins_url('wp-polls/polls-js.js'), array('jquery'), WP_POLLS_VERSION, true);
        wp_localize_script('wp-polls', 'pollsL10n', array(
-               'ajax_url' => admin_url('admin-ajax.php'),
+               'ajax_url' => home_url('wp-admin/admin-ajax.php'),
                'text_wait' => __('Your last request is still being processed. Please wait a while ...', 'wp-polls'),
                'text_valid' => __('Please choose a valid poll answer.', 'wp-polls'),
                'text_multiple' => __('Maximum number of choices allowed: ', 'wp-polls'),
@@ -230,7 +230,7 @@
                wp_enqueue_style('wp-polls-admin', plugins_url('wp-polls/polls-admin-css.css'), false, WP_POLLS_VERSION, 'all');
                wp_enqueue_script('wp-polls-admin', plugins_url('wp-polls/polls-admin-js.js'), array('jquery'), WP_POLLS_VERSION, true);
                wp_localize_script('wp-polls-admin', 'pollsAdminL10n', array(
-                       'admin_ajax_url' => admin_url('admin-ajax.php'),
+                       'admin_ajax_url' => home_url('wp-admin/admin-ajax.php'),
                        'text_direction' => is_rtl() ? 'right' : 'left',
                        'text_delete_poll' => __('Delete Poll', 'wp-polls'),
                        'text_no_poll_logs' => __('No poll logs available.', 'wp-polls'),
</pre>

If you don't have a better solution, I can make a pull request for this patch.

**Comment by lesterchan** [comment]
Sorry, I think using home_url() for that is wrong. I will still stick to admin_url() for it. For your case, I am not sure what is the best way around it. Maybe you can ask it on WP.org support forum.

See this https://github.com/lesterchan/wp-polls/pull/19 on why I make the change.

**Comment by dfisek** [comment]
I agree with you but currently it seems I don't have another option to get self-signed SSL sites working.

I created a topic in Wordpress forum, however I'm not hopeful. Since the whole admin-ajax.php thingy is a dirty hack by itself:
https://wordpress.org/support/topic/force_ssl_admin-and-admin-ajaxphp-problem

**Comment by lesterchan** [comment]
Yeap. I have no idea why WP want to use a wp-admin folder to handle AJAX calls.

**Comment by espellcaste** [comment]
@dfisek Maybe forcing ajax url to be http could work, I'm not sure how but maybe you could find a way around it.

**Comment by janrenn** [comment]
@dfisek use admin_url filter, e.g. lesterchan/wp-postratings#75
