### ISSUE TITLE
Open/Close Poll should update poll_latestpoll?

### ISSUE THREAD

**Issue by lesterchan** [lesterchan/wp-polls#48]
1. Check your current poll on the widget.
2. Close this poll.
3. Create a new poll.
4. Check if this poll is online.
5. Delete this new poll.
6. Check the widget. The message "Sorry, there are no polls available at the moment." appears.
7. Reopen the first poll.
8. Nothing happens, the message is still shown.

**Comment by espellcaste** [comment]
I'm not sure if it is related, but I haven't tested deeply so far, but when I use <?php get_poll();?> it doesn't fetch the current poll, I always go there and change <?php get_poll(2); ?> putting the poll ID.

At the moment, it worked, but I'll try to test it better in the future to see if that's a bug and if it is related with yours above.

**Comment by lesterchan** [comment]
@espellcaste I looked through the code, haha it is a bug. The code doesn't update poll_latestpoll when opening or closing poll.

**Comment by espellcaste** [comment]
Oh, good to know! Saved me some time to figure it out! =)

**Comment by espellcaste** [comment]
What if for some reason a site has multiple polls open at the same time? How is it going to be figure it out?

**Comment by lesterchan** [comment]
The latest poll should always be the open poll with the latest date

**Comment by espellcaste** [comment]
Got it!
