### ISSUE TITLE
Translation don't work

### ISSUE THREAD

**Issue by fredroo** [lesterchan/wp-polls#63]
put .po and mo in plugin folder, but don't work

use pt_BR.mo and pt_BR.po

how i can use?

**Comment by lesterchan** [comment]
The plugin now uses WP pologot https://make.wordpress.org/polyglots/ and hence it needs to be translated https://translate.wordpress.org/locale/pt-br/default/wp-plugins/wp-polls is only 15%, it needs to be 100% for it to be available.

**Comment by fredroo** [comment]
ok thanks

**Comment by fredroo** [comment]
how i can submit to you .po and .mo 100%

**Comment by lesterchan** [comment]
What is your username on WP.org? I can make you a translation editor?

**Comment by fredroo** [comment]
fredroo
yes please @lesterchan

**Comment by lesterchan** [comment]
Done https://make.wordpress.org/polyglots/2016/01/15/hi-there-i-am-the-plugin-author-for-3/ =)

Pending for review.
