### ISSUE TITLE
Even with username logging users can vote more than once

### ISSUE THREAD

**Issue by patrix87** [lesterchan/wp-polls#65]
Who Is Allowed To Vote?	
Allow To Vote : Registered Users Only

Logging Method
Poll Logging Method: Log by Username

User can still vote more than once by pressing Shit+F5 in chrome to refresh the page.

**Comment by lesterchan** [comment]
Are you using any caching plugin? Are you able to reproduce this problem with a fresh install of WP and the plugin?

**Comment by patrix87** [comment]
No caching plugins but I thing I was logged as admin if that matter?

**Comment by lesterchan** [comment]
Nope it doesn't matter. I just tried on my dev site https://lesterchan.net/wordpress_dev/ (the poll is on the right and there is two registered users voted)

and I can't reproduce the problem. Let me know if you can reproduce it on a fresh install of WP and WP-Polls, if not I can't do anything as well. I don't solve plugin/theme conflicts and hence fresh install is very important.

**Comment by patrix87** [comment]
here's the page http://multi-jeux.quebec/sondage-carte-exile/

Maybe Visual composer is interfering.

But if I go in Manage polls and then in the logs of that poll I see : 

There are a total of 0 recorded votes for this poll.
» 0 votes are cast by registered users
» 0 votes are cast by comment authors
» 0 votes are cast by guests

But in Edit I can see 4 Votes for the same answer *(all me)

If I set Cookie and IP it's working fine but I have no logs.

**Comment by lesterchan** [comment]
It is weird that you have no logs, could you check to see if wp_pollsip table has been created? If it has been created, there should be logs.

Again based on the site I tested, here are my logs.
![manage polls lester chan s wordpress plugins development wordpress](https://cloud.githubusercontent.com/assets/355829/12502821/554b6e40-c108-11e5-9418-15e3d5213860.png)

Looks like something weird is happening with your WP

**Comment by patrix87** [comment]
I do have a wp_pollsip table created and populated...

I think if there's a problem it's with the page that shows the polls directly...

Also, do you think you could add a setting to let other level of users, use the polls ?

I would like editor to be able to create one as well.

Thanks.

*(Logging by IP and Cookie works fine for me, I don't really need the username logging)

**Comment by patrix87** [comment]
Oh well the poll management was an easy fix :P 

Line 1881 of wp-polls.php

$role = get_role( 'editor' );
if( ! $role->has_cap( 'manage_polls' ) ) {
        $role->add_cap( 'manage_polls' );
 }

**Comment by lesterchan** [comment]
Found the problem https://wordpress.org/support/topic/1-vote-per-user?replies=11,

I will disable private IP
