### ISSUE TITLE
Allow user to take poll multiple times

### ISSUE THREAD

**Issue by chrisbeaman** [lesterchan/wp-polls#70]
I need to be able to let my users retake the poll or edit their responses.

**Comment by lesterchan** [comment]
Sorry that is not possible and I have no intention to add that anytime soon. But feel free to contribute to it as well.

**Comment by chrisbeaman** [comment]
I don't know how. Can I pay to add this feature?

**Comment by lesterchan** [comment]
Sorry I don't take up freelance job because I have a full time job and the contracts forbid me from taking side jobs.
