### ISSUE TITLE
after submitting a vote as a guest the plugin render the whole Home Page in the poll layout instead of showing the resullt

### ISSUE THREAD

**Issue by Moumokhtar** [lesterchan/wp-polls#83]
i'm having this weird issue, after submitting a vote as a guest or if i press on show result button , after the ajax load i get a duplicate of the site home page rendered in the Poll area, which destroys the layout.
if i reload the page the results show just fine, this issue happens only right after submitting a vote
![with-issue](https://cloud.githubusercontent.com/assets/7986441/20715691/a9035750-b658-11e6-884b-d2d597c71ca0.png)
![normal-after-refresh](https://cloud.githubusercontent.com/assets/7986441/20715690/a894fe0e-b658-11e6-8c80-32988be60b67.png)

**Comment by lesterchan** [comment]
Most likely a plugin or theme conflict. Check to see if it works on the default theme without any other plugins activated in the first place.

**Comment by Moumokhtar** [comment]
yeah it is working with the default theme, i wonder whats the conflict with my custom theme . what could cause the plugin to render all page content including meta tags and scripts in the layout like this ? and only when a guest user is trying to vote, where do you think this conflict may be happening, functions.php file ?

**Comment by lesterchan** [comment]
Sorry I don't really provide support for conflicts because it is time consuming. I provide the plugin as it is and bugs related to the plugin.

I will keep this issue open for others to contribute.

**Comment by Moumokhtar** [comment]
i found out what was causing this conflict, i had a function in my functions.php file that redirects non-admins to home page if they tried accessing admin area. i am not sure if i found the optimal solution but it works for me, i added an extra check to this function to check if an ajax call was made too, if not then do the redirect.
plugin working great now.
