### ISSUE TITLE
2.73.4 Crashes WP Site

### ISSUE THREAD

**Issue by krowvin** [lesterchan/wp-polls#90]
Greetings, wanted to let you know that when my wp-polls plugin updated to 2.73.4 it gave 500 errors to my entire site. I had to FTP in and change the wp-polls directory to wp-polls.old for it to continue working. I'm sure it's something on my end if nobody else is experiencing this. 

If they are though, changing the directory seems to fix it. I'm not really sure how to revert back to a previous version and still keep the old polls I made. 

Let me know if I can provide in logs to assist.

**Comment by lesterchan** [comment]
Yeap logs would be helpful! I upgraded two of my sites without issues.

**Comment by Blackbaud-JasonRikard** [comment]
Same issue with 2.73.4
`AH01071: Got error 'PHP message: PHP Parse error: syntax error, unexpected '[' in .../wp-content/plugins/wp-polls/wp-polls.php on line 468\n' `

**Comment by lesterchan** [comment]
Ah! What version of PHP are you using?

**Comment by Blackbaud-JasonRikard** [comment]
5.5.9 from Ubuntu 14.04.5 LTS‬.

**Comment by krowvin** [comment]
Oh, it gets weird, I enabled debug mode and went to refresh the web page to regenerate the error for logs. The site now loads with the plugin enabled. I've since turned debug off and wp-polls is still working. Let me see if it is stable through a restart.

**Comment by krowvin** [comment]
Running PHP 5.5.9-1ubuntu4.20
Ubuntu 14.04

**Comment by lesterchan** [comment]
@Blackbaud-JasonRikard thanks, I fixed it in 2.73.5. @krowvin is your error the same as @Blackbaud-JasonRikard ?

**Comment by krowvin** [comment]
I'm unable to generate a log for it, It seems to be working currently. Thanks for quick reply @lesterchan!
