### ISSUE TITLE
2.73.4 syntax error crashes site

### ISSUE THREAD

**Issue by iestyn** [lesterchan/wp-polls#91]
Hi there, 
There's a syntax error in wp-polls.php line 468:
$temp_pollvote .= "\t<form id=\"polls_form_$poll_question_id\" class=\"wp-polls-form\" action=\"" . sanitize_text_field( _SERVER['SCRIPT_NAME'] ) ."\" method=\"post\">\n";
Our sites crash until _SERVER is fixed up.
Cheers,
Iestyn.

**Comment by lesterchan** [comment]
It has been fixed in 2.73.5, Please refer to #90

**Comment by iestyn** [comment]
Oh wait - this is a duplicate. Sorry about that :-)
