### ISSUE TITLE
WP-Poll causes whitescreen of death when viewing themes

### ISSUE THREAD

**Issue by joshuasm** [lesterchan/wp-polls#93]
after activating WP-polls and go to change theme/live edit it gives whit screen of death.
logs: https://pastebin.com/zrHzYuyA

to get those logs i activated WP_DEBUG restarted httpd then activated the plugin tried viewing a live theme and then deactivating the plugin.
versions and stuff:
WP-Polls: Version 2.73.7
Wordpress: Version 4.8
latest mysql, php and apache

**Comment by lesterchan** [comment]
Not sure if I can help you with it. The logs don't indicate the source of the error is coming from WP-Polls. You are better off googling for "mysql_connect(): Headers and client library minor version mismatch"
