### ISSUE TITLE
Using wp_polls_update_poll only uses latest poll id

### ISSUE THREAD

**Issue by bderstine** [lesterchan/wp-polls#98]
I'm editing and saving custom fields with the **wp_polls_update_poll** action hook and found it only returns the latest poll id, even when editing an older poll, and causing data to be saved to the wrong poll id. I added a workaround in my custom function, but it would be easier if the action hook passed the current poll id being edited, rather than always returning the latest poll id.

Opened PR #97

**Comment by lesterchan** [comment]
Thanks for the PR, I agree with you =)
